# Generated by Django 2.0.7 on 2018-08-18 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180817_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kryptosuser',
            options={'ordering': ['-level', 'updated_at']},
        ),
        migrations.AddField(
            model_name='kryptosuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kryptosuser',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
