# Generated by Django 2.0.7 on 2018-08-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180818_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kryptosuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
