# Generated by Django 2.0.7 on 2018-08-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180818_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='filetype',
            field=models.CharField(choices=[('A', 'Audio'), ('I', 'Image'), ('G', 'Gif')], default='Audio', max_length=10),
        ),
        migrations.AddField(
            model_name='level',
            name='level_file',
            field=models.FileField(null=True, upload_to='level_images/'),
        ),
    ]
