# Generated by Django 2.0.7 on 2018-08-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180818_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_file',
            field=models.FileField(null=True, upload_to='level_files/'),
        ),
    ]
